### ISSUE TITLE
format value

### ISSUE THREAD

**Issue by MatheusPemill** [DarylBuckle/react-funnel-pipeline#3]
I'm trying to format the value of the funnel but i getting no results. I'm trying with the getRowValueStyle function.

**Comment by DarylBuckle** [comment]
Hi @MatheusPemill,

The Colours and Styles example has a working example of getRowValueStyle and demonstrates how to use it. The code can be found below;

[https://github.com/DarylBuckle/react-funnel-pipeline/blob/master/example/src/App.tsx](https://github.com/DarylBuckle/react-funnel-pipeline/blob/master/example/src/App.tsx)

```jsx
<FunnelChart 
  data={data}
  pallette={[
    '#ffb3ba',
    '#ffdfba',
    '#ffffba',
    '#baffc9',
    '#bae1ff',
  ]}
  getRowStyle={() => { return { margin: '0px'} }}
  getRowNameStyle={(row) => { return row.value < 15 ? { color: 'red'} : { color: 'black'}}}
  getRowValueStyle={(row) => { return row.value < 15 ? { color: 'red'} : { color: 'black'}}}
/>
```

If you are still having trouble after looking at this example, please could you provide some code demonstrating the issue you're having. Thanks.
